# File: azure-pipelines.yml
# Main AZP YAML file

name: $(Build.BuildId)

variables:
  - group: Common
  - group: Web
  - group: WebDevelopment # Change for release to production
  # Client Variables
  - name: PerceptiaOneVersion
    value: '0.0.1'
  - name: PerceptiaOneImageQualified
    value: '$(DockerHubOrg)/$(PerceptiaOneImageName)'

  

trigger:
  branches:
    include:
    - master
    - develop
    - feature/*
    - hotfix/*
    - release/*
  paths:
    include:
      - infrastructure/azp/*
      - '*'
    exclude:
    - README.md
    - infrastructure/*

pr:
  autoCancel: true
  branches:
    include:
    - master
    - develop
    - release/*
  paths:
    exclude:
    - README.md
    - infrastructure/*

jobs:
- job: 'TestPerceptiaOneUnitTests'
- job: 'BuildPerceptiaOneImage'
  variables:
  - name: ImageTagVersion
    value: '$(PerceptiaOneImageQualified):$(PerceptiaOneVersion)'
  - name: ImageTagVersionBuildId
    value: '$(ImageTagVersion)-build-$(Build.BuildId)'
  - name: ImageTagVersionBuildIdBranch
    value: '$(ImageTagVersionBuildId)-branch-$(Build.SourceBranchName)'
  - name: ImageTagVersionLatestBranch
    value: '$(ImageTagVersion)-build-latest-branch-$(Build.SourceBranchName)'
  pool:
    vmImage: 'Ubuntu-16.04'
  dependsOn: 'TestPerceptiaOneUnitTests'
  condition: and(succeeded(), or(eq(variables['forceBuild'], 'true'), not(startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/'))))
  steps:
  - task: Docker@1
    displayName: 'Build image'
    inputs:
      command: Build an image
      dockerFile: '$(system.defaultWorkingDirectory)/perceptia-one/Dockerfile'
      imageName: $(PerceptiaOneImageQualified)
      qualifyImageName: false
      arguments: "--build-arg REACT_APP_WEB_SERVER_HOST=$(WebServerHost) --build-arg REACT_APP_API_SERVER_HOST=$(ApiServerHost)"
  - template: 'infrastructure/azp/template/step/dockerStandardTagPush.yml'
    parameters:
      qualifiedImageName: $(PerceptiaOneImageQualified)
      versionLatestBranchTag: $(ImageTagVersionLatestBranch)
      versionBuildIdBranchTag: $(ImageTagVersionBuildIdBranch)
      versionTag: $(ImageTagVersion)
      versionBuildIdTag: $(ImageTagVersionBuildId)
      tagProduction: or(eq(variables[ 'productionTags'], 'true'), or(startsWith(variables['Build.SourceBranch'], 'refs/heads/master/'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')))
