# File: azure-pipelines.yml
# Main AZP YAML file

name: $(Build.BuildId)

variables:
  - group: Common
  - group: Web
  # Client Variables
  - name: PerceptiaOneVersion
    value: '0.0.1'
  - name: PerceptiaOneImageQualified
    value: '$(DockerHubOrg)/$(PerceptiaOneImageName)'

  

trigger:
  branches:
    include:
    - master
    - develop
    - feature/*
    - hotfix/*
  paths:
    include:
      - infrastructure/azp/*
      - '*'
    exclude:
    - README.md
    - infrastructure/*

pr:
  autoCancel: true
  branches:
    include:
    - master
    - develop
  paths:
    exclude:
    - README.md
    - infrastructure/*

jobs:
- job: 'TestPerceptiaOneUnitTests'
- job: 'BuildPerceptiaOneImage'
  variables:
  - name: ImageTagVersion
    value: '$(PerceptiaOneImageQualified):$(PerceptiaOneVersion)'
  - name: ImageTagVersionBuildId
    value: '$(ImageTagVersion)-build-$(Build.BuildId)'
  - name: ImageTagVersionBuildIdBranch
    value: '$(ImageTagVersionBuildId)-branch-$(Build.SourceBranchName)'
  - name: ImageTagVersionLatestBranch
    value: '$(ImageTagVersion)-build-latest-branch-$(Build.SourceBranchName)'
  pool:
    vmImage: 'Ubuntu-16.04'
  dependsOn: 'TestPerceptiaOneUnitTests'
  condition: and(succeeded(), eq(variables['forceBuild'], 'true'))
  steps:
  - task: Docker@1
    displayName: 'Build image'
    inputs:
      command: Build an image
      dockerFile: '$(system.defaultWorkingDirectory)/perceptia-one/Dockerfile'
      imageName: $(PerceptiaOneImageQualified)
      qualifyImageName: false
      arguments: |
        "--build-arg REACT_APP_WEB_SERVER_HOST=$(WebServerHost)"
        "--build-arg REACT_APP_API_SERVER_HOST=$(ApiServerHost)"
  - template: 'infrastructure/azp/template/step/dockerStandardTagPush.yml'
    parameters:
      qualifiedImageName: $(PerceptiaOneImageQualified)
      versionLatestBranchTag: $(ImageTagVersionLatestBranch)
      versionBuildIdBranchTag: $(ImageTagVersionBuildIdBranch)
      versionTag: $(ImageTagVersion)
      versionBuildIdTag: $(ImageTagVersionBuildId)
