kind: Service
apiVersion: v1
metadata:
  name: perceptiaone
  labels:
    label.perceptia.info/name: perceptiaone
    label.perceptia.info/instance: perceptiaone-1
    label.perceptia.info/version: "0.0.1"
    label.perceptia.info/managed-by: kubectl
    label.perceptia.info/component: server
    label.perceptia.info/type: frontend
    label.perceptia.info/part-of: perceptia-web
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: perceptiaWeb
spec:
  selector:
    app: perceptiaone
  ports:
  - protocol: TCP
    port: 443
    targetPort: https
    name: https
  - protocol: TCP
    port: 80
    targetPort: http
    name: http
  loadBalancerIP: 13.77.142.127
  type: LoadBalancer