apiVersion: apps/v1
kind: Deployment
metadata:
  name: perceptiaone-deployment
  labels:
    label.perceptia.info/name: perceptiaone
    label.perceptia.info/instance: perceptiaone-1
    label.perceptia.info/version: "0.0.1"
    label.perceptia.info/managed-by: kubectl
    label.perceptia.info/component: server
    label.perceptia.info/type: frontend
    label.perceptia.info/part-of: perceptia-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: perceptiaone
  template:
    metadata:
      labels:
        app: perceptiaone
        label.perceptia.info/name: perceptiaone
        label.perceptia.info/instance: perceptiaone-1
        label.perceptia.info/version: "0.0.1"
        label.perceptia.info/managed-by: kubectl
        label.perceptia.info/component: server
        label.perceptia.info/type: frontend
        label.perceptia.info/part-of: perceptia-web
    spec:
      containers:
      - name: gateway
        image: uwthalesians/perceptiaone:0.0.1-build-238-branch-develop
        ports:
        - containerPort: 443
          name: "https"
        - containerPort: 80
          name: "http"
        volumeMounts:
          - name: "encrypt"
            mountPath: "/etc/sitecert"
            readOnly: true
        resources:
          limits:
            cpu: 200m
            memory: 1Gi
      volumes:
        - name: "encrypt"
          secret:
            secretName: web-tls  